export const actionTypes = {
  SEND_LOGIN_REQUEST: '@@login/SEND_LOGIN_REQUEST',
  CLEAR_INPUTS_VALUES: '@@login/CLEAR_INPUTS_VALUES',
  SET_VALUE: '@@login/SET_VALUE',
  LOGIN_REQUEST_SUCCESS: '@@login/LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_ERROR: '@@login/LOGIN_REQUEST_ERROR',
};
