export enum actionTypes{
    GET_SOCKJS_CONNECTION = '@@game/GET_SOCKJS_CONNECTION',
    PUT_ROOMS = '@@game/PUT_ROOMS',
    SET_USER_LOGIN = '@@game/SET_USER_LOGIN',
    SUBSCRIBE_ROOM = '@@game/SUBSCRIBE_ROOM',
    JOIN_ROOM = '@@game/JOIN_ROOM',
    PLAY_WITH_BOT = '@@game/PLAY_WITH_BOT',
    CREATE_ROOM = '@@game/CREATE_ROOM',
    SET_ACTUAL_ROOM = '@@game/SET_ACTUAL_ROOM',
    DELETE_ROOM = '@@game/DELETE_ROOM',
    GET_STEP_ORDER = '@@game/GET_STEP_ORDER',
    SET_STEP_ORDER = '@@game/SET_STEP_ORDER',
    DO_TIC_STEP = '@@game/DO_TIC_STEP',
    SET_STEP_HISTORY = '@@game/SET_STEP_HISTORY'
}
