export enum actionTypes {
    SEND_REGISTRATION_REQUEST = '@@registration/SEND_REGISTRATION_REQUEST',
    CLEAR_INPUTS_VALUES = '@@registration/CLEAR_INPUTS_VALUES',
    SET_VALUE = '@@registration/SET_VALUE',
    REGISTRATION_REQUEST_SUCCESS = '@@registration/REGISTRATION_REQUEST_SUCCESS',
    REGISTRATION_REQUEST_ERROR = '@@registration/REGISTRATION_REQUEST_ERROR',
    DEFAULT = '@@registration/DEFAULT',
}
